### ISSUE TITLE
Fix previews

### ISSUE THREAD

**Issue by jdwillemse** [futurice/masifunde-fe#297]
The previews are not working for all pages. The cause is unknown. See blog https://masifunde-preview.netlify.app/blog/weltwaerts-mal-anders/

Show a banner at the top of the site indicating that the page is in preview mode. The editors do not know when they are previewing content (maybe explain what preview means in the banner)

**Comment by denisw** [comment]
@felixMasi I think this is fixed now. The issue simply seems to have been that auto-publishing was disabled for the _masifunde-preview_ site on Netlify. I enabled it now and confirmed that new content is now visible in the preview.
